import csv
from dataclasses import dataclass
from typing import List

header = ["MELDETATBESTAND","SPECIES_CODE","SPECIES","LAB_SEQUENCE_ID","DEMIS_NOTIFICATION_ID","STATUS","DATE_OF_SAMPLING","DATE_OF_RECEIVING","DATE_OF_SEQUENCING","SEQUENCING_INSTRUMENT","SEQUENCING_PLATFORM","ADAPTER","PRIMER_SCHEME","SEQUENCING_STRATEGY","ISOLATION_SOURCE_CODE","ISOLATION_SOURCE","HOST_SEX","HOST_BIRTH_MONTH","HOST_BIRTH_YEAR","SEQUENCING_REASON","GEOGRAPHIC_LOCATION","ISOLATE","AUTHOR","NAME_AMP_PROTOCOL","PRIME_DIAGNOSTIC_LAB.DEMIS_LAB_ID","PRIME_DIAGNOSTIC_LAB.NAME","PRIME_DIAGNOSTIC_LAB.ADDRESS","PRIME_DIAGNOSTIC_LAB.POSTAL_CODE","PRIME_DIAGNOSTIC_LAB.CITY","PRIME_DIAGNOSTIC_LAB.FEDERAL_STATE","PRIME_DIAGNOSTIC_LAB.COUNTRY","PRIME_DIAGNOSTIC_LAB.EMAIL","SEQUENCING_LAB.DEMIS_LAB_ID","SEQUENCING_LAB.NAME","SEQUENCING_LAB.ADDRESS","SEQUENCING_LAB.POSTAL_CODE","SEQUENCING_LAB.CITY","SEQUENCING_LAB.FEDERAL_STATE","SEQUENCING_LAB.COUNTRY","SEQUENCING_LAB.EMAIL","REPOSITORY_NAME","REPOSITORY_LINK","REPOSITORY_ID","UPLOAD_DATE","UPLOAD_STATUS","UPLOAD_SUBMITTER","FILE_1_NAME","FILE_1_SHA256SUM","FILE_2_NAME","FILE_2_SHA256SUM"]

@dataclass
class CsvRow:
    MELDETATBESTAND: str
    SPECIES_CODE: str
    SPECIES: str
    LAB_SEQUENCE_ID: str
    DEMIS_NOTIFICATION_ID: str
    STATUS: str
    DATE_OF_SAMPLING: str
    DATE_OF_RECEIVING: str
    DATE_OF_SEQUENCING: str
    SEQUENCING_INSTRUMENT: str
    SEQUENCING_PLATFORM: str
    ADAPTER: str
    PRIMER_SCHEME: str
    SEQUENCING_STRATEGY: str
    ISOLATION_SOURCE_CODE: str
    ISOLATION_SOURCE: str
    HOST_SEX: str
    HOST_BIRTH_MONTH: str
    HOST_BIRTH_YEAR: str
    SEQUENCING_REASON: str
    GEOGRAPHIC_LOCATION: str
    ISOLATE: str
    AUTHOR: str
    NAME_AMP_PROTOCOL: str
    PRIME_DIAGNOSTIC_LAB_DEMIS_LAB_ID: str
    PRIME_DIAGNOSTIC_LAB_NAME: str
    PRIME_DIAGNOSTIC_LAB_ADDRESS: str
    PRIME_DIAGNOSTIC_LAB_POSTAL_CODE: str
    PRIME_DIAGNOSTIC_LAB_CITY: str
    PRIME_DIAGNOSTIC_LAB_FEDERAL_STATE: str
    PRIME_DIAGNOSTIC_LAB_COUNTRY: str
    PRIME_DIAGNOSTIC_LAB_EMAIL: str
    SEQUENCING_LAB_DEMIS_LAB_ID: str
    SEQUENCING_LAB_NAME: str
    SEQUENCING_LAB_ADDRESS: str
    SEQUENCING_LAB_POSTAL_CODE: str
    SEQUENCING_LAB_CITY: str
    SEQUENCING_LAB_FEDERAL_STATE: str
    SEQUENCING_LAB_COUNTRY: str
    SEQUENCING_LAB_EMAIL: str
    REPOSITORY_NAME: str
    REPOSITORY_LINK: str
    REPOSITORY_ID: str
    UPLOAD_DATE: str
    UPLOAD_STATUS: str
    UPLOAD_SUBMITTER: str
    FILE_1_NAME: str
    FILE_1_SHA256SUM: str
    FILE_2_NAME: str
    FILE_2_SHA256SUM: str


def read_csv(csv_path: str) -> List[CsvRow]:
    with open(csv_path, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile, delimiter=';')
        rows = []
        for r in reader:
            cleaned = {}
            for field in header:
                val = r.get(field, "")
                if val is None:
                    val = ""
                else:
                    val = str(val).strip()
                cleaned[field.replace('.','_')] = val
            rows.append(CsvRow(**cleaned))
        return rows
